### ISSUE TITLE
Code for Point-PN

### ISSUE THREAD

**Issue by Liuyunming1999** [ZrrSkywalker/Point-NN#4]
Thank you very much for your work. I wonder if you can provide the Point-NN code in your paper？

**Comment by ZrrSkywalker** [comment]
We are organizing the PN code and will release it in a few days. Thanks for your waiting.

**Comment by zhuqiang00099** [comment]
期待Point-PN代码

**Comment by ZrrSkywalker** [comment]
@Liuyunming1999 @zhuqiang00099 
Thanks for your waiting. The code for Point-PN has been released.

**Comment by Cipher-zzz** [comment]
@ZrrSkywalker Thank you for your wonderful work and quick update. 

I got this error when I ran point_pn:
`Traceback (most recent call last):
  File "run_pn_mn40.py", line 15, in <module>
    import models as models
  File "\Point-NN-main\models\__init__.py", line 6, in <module>
    from .point_pn import Point_PN_mn40, Point_PN_scan
ImportError: cannot import name 'Point_PN_mn40' from 'models.point_pn' (\Point-NN-main\models\point_pn.py)`

There is no model class in point_pn.py. Could you check it and update the file?

**Comment by ZrrSkywalker** [comment]
@Cipher-zzz Sorry for this. We have rectified the code. Reach us if there has further issue.

**Comment by Cipher-zzz** [comment]
@ZrrSkywalker Thanks for your quick response, that works!
